name: C Build Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (if any)
      # For Ubuntu, GCC is usually pre-installed, but just in case
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install build-essential -y

      # Compile the code
      - name: Compile C Program
        run: gcc -o index index.c

      # Run the compiled program
      - name: Run Program
        run: ./index
